support rename table
selectdb/ccr-syncer pull request #119
Opened 2024-07-06 13:45 UTC by lsy3993

2024-07-06 13:54 UTC, lsy3993 commented
kitex version is lower than dev branch, just close

2024-08-22 14:02 UTC, smallx requested changes

2024-08-22 14:02 UTC, smallx commented on pkg/ccr/base/spec.go
> +	// rename table may be 'rename table', 'rename rollup', 'rename partition' and 'rename column'
remove `and 'rename column'` due to https://github.com/selectdb/ccr-syncer/pull/139

2024-08-22 14:02 UTC, smallx commented on pkg/ccr/base/spec.go
> +	// todo rename column
remove this due to https://github.com/selectdb/ccr-syncer/pull/139

2024-08-29 09:05 UTC, w41ter commented on pkg/ccr/job.go
> +		return xerror.Errorf(xerror.Normal, "rename table is not supported when table sync")
We don't support sync rename operation to the downstream, ignore this binlog directly, and remember to update the saved src name.

2024-08-29 09:05 UTC, w41ter commented on pkg/ccr/job.go
> +	err = j.IDest.RenameTable(destTableName, renameTable)
Once the rename operation is executed success, the cached metadata in destMeta is staled, try refresh it:

```
j.destMeta.GetTables()
```

2024-08-29 09:05 UTC, w41ter commented on pkg/ccr/job.go
> +	err = j.IDest.RenameTable(destTableName, renameTable)
the srcMeta should be updated in both db and table sync.

```
j.srcMeta.GetTables()
```

2024-08-31 14:46 UTC, lsy3993 commented
new PR is : #147

2024-09-09 06:48 UTC, lsy3993 commented
New PR is https://github.com/selectdb/ccr-syncer/pull/147, close this PR

2024-09-09 06:48 UTC, closed without merging