add db sync test case for test_ts_col_drop test_ts_col_alter_type test_ts_col_order_by
selectdb/ccr-syncer pull request #228
Opened 2024-11-11 13:03 UTC by wyxxxcat

issue : https://github.com/apache/doris/issues/43560

2024-11-12 14:26 UTC, dataroaring approved these changes
LGTM

2024-11-13 07:42 UTC, w41ter commented
Please place cases in separate directories, so that we can run those cases in parallel. @wyxxxcat

2024-11-13 07:53 UTC, w41ter requested changes

2024-11-13 07:53 UTC, w41ter commented on regression-test/suites/db_sync/column/alter_type/test_ds_col_alter_type.groovy
> +    helper.ccrJobCreate()
```suggestion
	helper.ccrJobDelete()
    helper.ccrJobCreate()
```

2024-11-13 07:53 UTC, w41ter commented on regression-test/suites/db_sync/column/alter_type/test_ds_col_alter_type.groovy
> +    helper.ccrJobCreate()
We will run a case twice.

2024-11-13 07:53 UTC, w41ter commented on regression-test/suites/db_sync/column/alter_type/test_ds_col_alter_type.groovy
> +                                has_count(1), 30))
It should be has_count(2) ?

2024-11-13 07:53 UTC, w41ter commented on regression-test/suites/db_sync/column/drop/test_ds_col_drop_key_col.groovy
> +    helper.ccrJobCreate()
```suggestion
	helper.ccrJobDelete()
    helper.ccrJobCreate()
```

2024-11-13 07:53 UTC, w41ter commented on regression-test/suites/db_sync/column/drop/test_ds_col_drop_val_col.groovy
> +    helper.ccrJobCreate()
```suggestion
	helper.ccrJobDelete()
    helper.ccrJobCreate()
```

2024-11-13 07:53 UTC, w41ter commented on regression-test/suites/db_sync/column/alter_type/test_ds_col_alter_type.groovy
> +    sql "DROP TABLE IF EXISTS ${dbName}.${tableName}"
```suggestion
	helper.enableDbBinlog()
    sql "DROP TABLE IF EXISTS ${dbName}.${tableName}"
```

2024-11-13 07:53 UTC, w41ter commented on regression-test/suites/db_sync/column/alter_type/test_ds_col_alter_type.groovy
> +    sql "DROP TABLE IF EXISTS ${dbName}.${tableName}"
ditto, for all cases

2024-11-13 07:53 UTC, w41ter commented on regression-test/suites/db_sync/column/order_by/test_ds_col_order_by.groovy
> +        // Field == 'id' && 'Key' == 'YES'
```suggestion
```

2024-11-19 07:59 UTC, w41ter approved these changes

2024-11-19 08:00 UTC, merged