Add ts sync test for tbl model
selectdb/ccr-syncer pull request #244
Opened 2024-11-19 07:23 UTC by wyxxxcat

2024-11-19 08:04 UTC, w41ter commented on regression-test/suites/db_sync/table/aggregate/test_ds_tbl_aggregate.groovy
> +    sql "DROP TABLE IF EXISTS TEST_${dbName}.${tableName}"
target_sql?

2024-11-19 08:08 UTC, wyxxxcat commented on regression-test/suites/db_sync/table/aggregate/test_ds_tbl_aggregate.groovy
> +    sql "DROP TABLE IF EXISTS TEST_${dbName}.${tableName}"
sorry, done

2024-11-22 09:42 UTC, w41ter requested changes

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/db_sync/table/aggregate/test_ds_tbl_aggregate.groovy
> +    sql_res = sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def sql_res = sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/db_sync/table/aggregate/test_ds_tbl_aggregate.groovy
> +    target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/db_sync/table/duplicate/test_ds_tbl_duplicate.groovy
> +    sql_res = sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def sql_res = sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/db_sync/table/duplicate/test_ds_tbl_duplicate.groovy
> +    target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/db_sync/table/aggregate/test_ds_tbl_aggregate.groovy
> +    def tableName = "test_ds_tbl_aggregate_table"
```suggestion
    def tableName = "tbl_" + helper.randomSuffix()
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/db_sync/table/duplicate/test_ds_tbl_duplicate.groovy
> +    def tableName = "test_ds_tbl_duplicate_table"
```suggestion
    def tableName = "tbl_" + helper.randomSuffix()
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/db_sync/table/unique/test_ds_tbl_unique.groovy
> +    def tableName = "test_ds_tbl_unique_table"
```suggestion
    def tableName = "tbl_" + helper.randomSuffix()
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/db_sync/table/unique/test_ds_tbl_unique.groovy
> +    sql_res = sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def sql_res = sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/db_sync/table/unique/test_ds_tbl_unique.groovy
> +    target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/table_sync/table/aggregate/test_ts_tbl_aggregate.groovy
> +    def tableName = "test_ts_tbl_aggregate_table"
```suggestion
    def tableName = "tbl_" + helper.randomSuffix()
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/table_sync/table/aggregate/test_ts_tbl_aggregate.groovy
> +    sql_res = sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def sql_res = sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/table_sync/table/aggregate/test_ts_tbl_aggregate.groovy
> +    target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/table_sync/table/duplicate/test_ts_tbl_duplicate.groovy
> +    def tableName = "test_ts_tbl_duplicate_table"
```suggestion
    def tableName = "tbl_" + helper.randomSuffix()
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/table_sync/table/duplicate/test_ts_tbl_duplicate.groovy
> +    sql_res = sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def sql_res = sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/table_sync/table/duplicate/test_ts_tbl_duplicate.groovy
> +    target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/table_sync/table/unique/test_ts_tbl_unique.groovy
> +    def tableName = "test_ts_tbl_unique_table"
```suggestion
    def tableName = "tbl_" + helper.randomSuffix()
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/table_sync/table/unique/test_ts_tbl_unique.groovy
> +    sql_res = sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def sql_res = sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 09:42 UTC, w41ter commented on regression-test/suites/table_sync/table/unique/test_ts_tbl_unique.groovy
> +    target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```suggestion
    def target_res = target_sql "SHOW CREATE TABLE ${tableName}"
```

2024-11-22 12:51 UTC, w41ter approved these changes

2024-11-22 12:51 UTC, w41ter approved these changes

2024-11-22 12:52 UTC, merged