[feat](binlog) Add Support recover binlog
selectdb/ccr-syncer pull request #284
Opened 2024-11-30 13:32 UTC by Vallishp

support recover table, recover partition

2024-12-04 07:22 UTC, dataroaring approved these changes
LGTM

2024-12-09 03:59 UTC, w41ter requested changes
Rest LGTM

2024-12-09 03:59 UTC, w41ter commented on pkg/ccr/record/recover_info.go
> +	 */
Please add the above check, and also check if the table name and partition name exist.

2024-12-09 03:59 UTC, w41ter commented on pkg/ccr/job.go
> +	if recoverInfo.PartitionName == "" {
Consider adding a helper function `IsRecoverPartition() bool { return record.PartitionId == -1 }`, and change below line to:

```suggestion
	if recoverInfo.IsRecoverPartition() {
```

2024-12-11 09:31 UTC, w41ter approved these changes

2024-12-11 09:40 UTC, merged