Fix error for alter column default value CURRENT_TIMESTAMP
selectdb/ccr-syncer pull request #293
Opened 2024-12-04 10:30 UTC by wyxxxcat

```
[2024-12-04 18:19:15.863]  WARN job sync failed, job: test, err: [normal] Error 1105 (HY000): errCode = 2, detailMessage = date literal [CURRENT_] is invalid: Unknown time-zone ID: TIMESTAMP
exec sql ALTER TABLE `t` ADD COLUMN `compute_time` datetimev2(0) NULL DEFAULT "CURRENT_TIMESTAMP" COMMENT "计算时间" AFTER `pick_order_big_num` failed
github.com/selectdb/ccr_syncer/pkg/ccr/base.(*Spec).DbExec
    /home/wyxxxcat/ccr-syncer/pkg/ccr/base/spec.go:1166
github.com/selectdb/ccr_syncer/pkg/ccr/base.(*Spec).LightningSchemaChange
    /home/wyxxxcat/ccr-syncer/pkg/ccr/base/spec.go:1245
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).handleLightningSchemaChange
    /home/wyxxxcat/ccr-syncer/pkg/ccr/job.go:2102
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).handleBinlog
    /home/wyxxxcat/ccr-syncer/pkg/ccr/job.go:2720
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).handleBinlogs
    /home/wyxxxcat/ccr-syncer/pkg/ccr/job.go:2657
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).incrementalSync
    /home/wyxxxcat/ccr-syncer/pkg/ccr/job.go:2834
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).dbSync
    /home/wyxxxcat/ccr-syncer/pkg/ccr/job.go:2895
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).sync
    /home/wyxxxcat/ccr-syncer/pkg/ccr/job.go:2912
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).run
    /home/wyxxxcat/ccr-syncer/pkg/ccr/job.go:2970
github.com/selectdb/ccr_syncer/pkg/ccr.(*Job).Run
    /home/wyxxxcat/ccr-syncer/pkg/ccr/job.go:3091
github.com/selectdb/ccr_syncer/pkg/ccr.(*JobManager).runJob.func1
    /home/wyxxxcat/ccr-syncer/pkg/ccr/job_manager.go:166
runtime.goexit
    /usr/local/go/src/runtime/asm_amd64.s:1700 job=test line=ccr/job.go:2975
```

2024-12-04 14:21 UTC, dataroaring approved these changes
LGTM

2024-12-09 03:45 UTC, w41ter requested changes
Here is the syntax definition about column default value:

```
opt_default_value ::=
    /* Empty */
    {:
        RESULT = ColumnDef.DefaultValue.NOT_SET;
    :}
    | KW_DEFAULT STRING_LITERAL:value
    {:
        RESULT = new ColumnDef.DefaultValue(true, value);
    :}
    | KW_DEFAULT KW_NULL
    {:
        RESULT = ColumnDef.DefaultValue.NULL_DEFAULT_VALUE;
    :}
    | KW_DEFAULT KW_CURRENT_TIMESTAMP
    {:
        RESULT = ColumnDef.DefaultValue.CURRENT_TIMESTAMP_DEFAULT_VALUE;
    :}
    | KW_DEFAULT KW_CURRENT_TIMESTAMP LPAREN INTEGER_LITERAL:precision RPAREN
    {:
        RESULT = ColumnDef.DefaultValue.currentTimeStampDefaultValueWithPrecision(precision);
    :}
    | KW_DEFAULT KW_BITMAP_EMPTY
    {:
        RESULT = ColumnDef.DefaultValue.BITMAP_EMPTY_DEFAULT_VALUE;
    :}
    | KW_DEFAULT INTEGER_LITERAL:value
    {:
        RESULT = new ColumnDef.DefaultValue(true, value);
    :}
    | KW_DEFAULT LARGE_INTEGER_LITERAL:value
    {:
        RESULT = new ColumnDef.DefaultValue(true, value);
    :}
    | KW_DEFAULT DECIMAL_LITERAL:value
    {:
        RESULT = new ColumnDef.DefaultValue(true, value);
    :}
    
```

2024-12-09 03:45 UTC, w41ter commented on pkg/ccr/base/spec.go
> +	sql = strings.ReplaceAll(sql, "\"CURRENT_TIMESTAMP\"", "CURRENT_TIMESTAMP")
1. The CREATE_TABLE binlog should fix this issue too.
2. consider replacing with `DEFAULT "CURRENT_TIMESTAMP"` to `DEFAULT CURRENT_TIMESTAMP`
3. please add some test cases.

2024-12-16 09:28 UTC, w41ter approved these changes

2024-12-16 09:30 UTC, w41ter approved these changes

2024-12-16 09:30 UTC, merged