create a handler can list job details
selectdb/ccr-syncer pull request #66
Opened 2024-04-26 14:55 UTC by lsy3993

request is : 
```
curl -X POST -H "Content-Type: application/json" -d '{
        "name": "ccr_job_name"
    }' http://127.0.0.1:9190/job_detail
```

response is : 
```
{"success":true,"job detail":"{\"sync_type\":1,\"name\":\"ccr_test2\",
\"src\":{\"host\":\"xxx.xx.xx.xx\",
             \"port\":\"9030\",
             \"thrift_port\":\"9020\",
            \"is_master\":false,
            \"frontends\":[{\"host\":\"xxx.xx.xx.xx\",\"port\":\"9030\",\"thrift_port\":\"9020\",\"is_master\":true}],
            \"user\":\"root\",
            \"password\":\"\",
            \"cluster\":\"\",
            \"database\":\"test\",
             \"db_id\":10025,
              \"table\":\"table_a\",
              \"table_id\":10102},\  
"dest\":{\"host\":\"xxx.xx.xx.xx\",
              \"port\":\"9030\",
              \"thrift_port\":\"9020\",
              \"is_master\":false,
              \"frontends\":[{\"host\":\"xxx.xx.xx.xx\",\"port\":\"9030\",\"thrift_port\":\"9020\",\"is_master\":true}],
             \"user\":\"root\",
              \"password\":\"\",
              \"cluster\":\"\",
              \"database\":\"test\",
              \"db_id\":10025,
              \"table\":\"table_b\",
              \"table_id\":11411},
              \"skip_error\":false,
              \"state\":0}"}
```

2024-04-26 14:56 UTC, lsy3993 commented
@w41ter Is this response format correct?

2024-04-28 03:43 UTC, w41ter requested changes

2024-04-28 03:43 UTC, w41ter commented on pkg/service/http_service.go
> +		JobDetail string `json:"job detail"`
```suggestion
		JobDetail string `json:"job_detail"`
```

2024-04-28 03:43 UTC, w41ter commented on pkg/service/http_service.go
> +		}
```suggestion
		}
		return
```

2024-04-28 03:43 UTC, w41ter commented on pkg/service/http_service.go
> +			defaultResult: newErrorResult(err.Error()),
```suggestion
			defaultResult: newErrorResult("name is empty"),
```

2024-04-28 07:59 UTC, w41ter approved these changes

2024-04-28 07:59 UTC, w41ter commented on pkg/service/http_service.go
> +		}
```suggestion
		}
		return
```

2024-04-28 08:00 UTC, merged